Novi/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Novi.Models;
using Novi.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Novi.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleRepository _articleRepository;
        private readonly ICategoryRepository _categoryRepository;

        // Constructor to build-in the 2 repositories-data into the system via starticleup (services.AddScoped<IArticleRepository, MockArticleRepository>();)
        public ArticleController(IArticleRepository articleRepository, ICategoryRepository categoryRepository)
        {
            _articleRepository = articleRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: /<controller>/
        //public IActionResult List()
        //{
        //    //ViewBag.CurrentCategory = "Cheese cakes";

        //    //return View(_articleRepository.AllArticles);
        //    ArticlesListViewModel articlesListViewModel = new ArticlesListViewModel();
        //    articlesListViewModel.Articles = _articleRepository.AllArticles;

        //    articlesListViewModel.CurrentCategory = "Cheese cakes";
        //    return View(articlesListViewModel);
        //}
        // Controllers handle incomming requests with an action

        public ViewResult List(string category)
        {
            IEnumerable<Article> articles;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                articles = _articleRepository.AllArticles.OrderBy(p => p.ArticleId);
                currentCategory = "All articles";
            }
            else
            {
                articles = _articleRepository.AllArticles.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.ArticleId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new ArticlesListViewModel
            {
                Articles = articles,
                CurrentCategory = currentCategory
            });
        }


        public IActionResult Details(int id)
        // ViewBag: The most basic way to show data on the dynamic cshtml-file
        //ViewBag.CurrentCategory = "surrealistic";
        {
            var article = _articleRepository.GetArticleById(id);
            if (article == null)
                return NotFound(); // send back a 404 not found

        //    [HttpPost]
        //    public IActionResult update(Article article)
        //    {
        //        var items = _article.GetShoppingCartItems();
        //        _shoppingCart.ShoppingCartItems = items;

        //        if (_shoppingCart.ShoppingCartItems.Count == 0)
        //        {
        //            ModelState.AddModelError("", "Your cart is empty, add some arts first");
        //        }

        //        if (ModelState.IsValid)
        //        {
        //            _orderRepository.CreateOrder(order);
        //            _shoppingCart.ClearCart();
        //            return RedirectToAction("CheckoutComplete");
        //        }
        //        return View(order);
        //    }


            return View(article); // View: build-in methode from asp.net core to view a .cshtml-file
        }
    }
}

Novi/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Novi.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Novi/Views/Shared/_ArticleCart.cshtml
@model Article


    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@Model.ImageThumbnailUrl" alt="">
            <div class="caption">
                <h3 class="pull-right">@Model.Price.ToString("c")</h3>
                <h3>
                    <a asp-controller="Article"
                       asp-action="Details"
                       asp-route-id="@Model.ArticleId">@Model.Name</a>
                </h3>
                <p>@Model.Description</p>

                <form asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-articleId="@Model.ArticleId" method="post" role="form">
                    <div class="form-group">
                        <label asp-for="HireFrom" class="col-md-2 control-label"></label>
                        <div class="col-md-5">
                            <input asp-for="HireFrom" class="form-control" />
                            <span asp-validation-for="HireFrom" class="text-danger"></span>
                        </div>


                        <label asp-for="HireTill" class="col-md-2 control-label"></label>
                        <div class="col-md-5">
                            <input asp-for="HireTill" class="form-control" />
                            <span asp-validation-for="HireTill" class="text-danger"></span>

                        </div>

                        <div class="col-md-offset-2 col-md-5">
                            <input type="submit" class="btn btn-primary" value="Add to cart" />
                        </div>
                    </div>
                </form>


                    @*</div>

            <div class="addToCart">
                    <p class="button">
                        <a class="btn btn-primary"
                           asp-controller="ShoppingCart"
                           asp-action="AddToShoppingCart"
                           asp-route-articleId="@Model.ArticleId">Add to cart</a>
                    </p>
                </div>
        </div>*@
                </div>
</div>
</div>

Novi/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Novi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- standaard templatelayout where other Vieuws can refer to-->
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("CategoryMenu")
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Novi's ART Shop'" src="~/Images/logo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>